import { Pool, type PoolClient } from 'pg'
import type { Article, Category, Fold, Language, Status } from './types'

/**
 * Serverless functions get one pool per warm instance, and RDS counts every one
 * of those against max_connections. Keep the pool small and let idle connections
 * go quickly, so a burst of instances doesn't exhaust the server.
 */
function makePool(): Pool {
  const connectionString = process.env.DATABASE_URL
  if (!connectionString) {
    throw new Error('DATABASE_URL is not set — point it at your Postgres/RDS instance.')
  }
  return new Pool({
    connectionString,
    max: Number(process.env.PG_POOL_MAX ?? 3),
    idleTimeoutMillis: 10_000,
    connectionTimeoutMillis: 10_000,
    ssl: sslConfig(),
  })
}

/**
 * RDS terminates TLS with an Amazon-issued cert that isn't in Node's trust store.
 * Supply the RDS CA bundle in RDS_CA_CERT to verify it properly; without one we
 * still encrypt but skip verification, which is the common RDS-on-Vercel setup.
 * DATABASE_SSL=disable is for a plaintext local Postgres.
 */
function sslConfig() {
  if (process.env.DATABASE_SSL === 'disable') return undefined
  const ca = process.env.RDS_CA_CERT
  return ca ? { ca, rejectUnauthorized: true } : { rejectUnauthorized: false }
}

// Survives dev hot-reloads, which would otherwise leak a pool per edit.
const globalForPg = globalThis as unknown as { _pool?: Pool; _schema?: Promise<void> }

export function pool(): Pool {
  globalForPg._pool ??= makePool()
  return globalForPg._pool
}

/* ---------------------------------------------------------------- queries */

type Row = Record<string, unknown>

/**
 * Translates the @named placeholders these queries are written with into the
 * positional $1..$n that pg expects. A name repeated in one statement is bound
 * once per occurrence, which is what the callers below rely on.
 */
function bind(sql: string, params: Record<string, unknown>): [string, unknown[]] {
  const values: unknown[] = []
  const text = sql.replace(/@(\w+)/g, (_m, name: string) => {
    values.push(params[name] ?? null)
    return `$${values.length}`
  })
  return [text, values]
}

async function all<T = Row>(sql: string, params: Record<string, unknown> = {}): Promise<T[]> {
  await ensureSchema()
  const [text, values] = bind(sql, params)
  const res = await pool().query(text, values)
  return res.rows as T[]
}

async function one<T = Row>(sql: string, params: Record<string, unknown> = {}): Promise<T | null> {
  const rows = await all<T>(sql, params)
  return rows[0] ?? null
}

async function run(sql: string, params: Record<string, unknown> = {}): Promise<void> {
  await all(sql, params)
}

/* ----------------------------------------------------------------- schema */

const TABLES = `
CREATE TABLE IF NOT EXISTS articles (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category      TEXT NOT NULL DEFAULT 'general',
  raw_text      TEXT NOT NULL,
  title         TEXT NOT NULL DEFAULT '',
  body          TEXT NOT NULL DEFAULT '',
  district      TEXT,
  language      TEXT NOT NULL DEFAULT 'mr',
  release_no    TEXT,
  office        TEXT,
  department    TEXT,
  attribution   TEXT,
  bullets       TEXT NOT NULL DEFAULT '[]',
  dateline      TEXT,
  byline        TEXT,
  status        TEXT NOT NULL DEFAULT 'pending',
  submitted_by  TEXT NOT NULL DEFAULT 'dlo',
  submitted_at  TEXT NOT NULL,
  approved_at   TEXT,
  fold_date     TEXT NOT NULL,
  poster_url    TEXT,
  source_url    TEXT
);

CREATE TABLE IF NOT EXISTS folds (
  "date"        TEXT PRIMARY KEY,
  article_order TEXT NOT NULL DEFAULT '[]',
  finalized_at  TEXT
);
`

/**
 * CREATE TABLE IF NOT EXISTS never adds a column to a table that already exists,
 * so columns introduced after someone's database was created need this.
 */
const MIGRATIONS = `
ALTER TABLE articles ADD COLUMN IF NOT EXISTS byline     TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS category   TEXT NOT NULL DEFAULT 'general';
ALTER TABLE articles ADD COLUMN IF NOT EXISTS poster_url TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS source_url TEXT;
`

const INDEXES = `
CREATE INDEX IF NOT EXISTS idx_articles_fold   ON articles(fold_date, status);
CREATE INDEX IF NOT EXISTS idx_articles_dist   ON articles(district, status);
CREATE INDEX IF NOT EXISTS idx_articles_cat    ON articles(category, fold_date);
CREATE INDEX IF NOT EXISTS idx_articles_source ON articles(source_url);
`

/**
 * Runs once per process. Two instances cold-starting together can race inside
 * IF NOT EXISTS and one loses with a duplicate-object error; that means the
 * other created it, so it is safe to swallow.
 */
export function ensureSchema(): Promise<void> {
  globalForPg._schema ??= (async () => {
    let client: PoolClient | undefined
    try {
      client = await pool().connect()
      // Must run before the indexes: an index over a column that MIGRATIONS has
      // not added yet fails outright, and that failure takes every route with it.
      for (const batch of [TABLES, MIGRATIONS, INDEXES]) {
        try {
          await client.query(batch)
        } catch (err) {
          if (!isDuplicateObject(err)) throw err
        }
      }
    } catch (err) {
      globalForPg._schema = undefined // let the next request retry
      throw err
    } finally {
      client?.release()
    }
  })()
  return globalForPg._schema
}

function isDuplicateObject(err: unknown): boolean {
  const code = (err as { code?: string })?.code
  return code === '23505' || code === '42P07' || code === '42701'
}

/* ---------------------------------------------------------------- mapping */

function toArticle(r: Row): Article {
  return {
    id: Number(r.id),
    category: (r.category as Category) ?? 'general',
    raw_text: r.raw_text as string,
    title: r.title as string,
    body: r.body as string,
    district: (r.district as string) ?? null,
    language: r.language as Language,
    release_no: (r.release_no as string) ?? null,
    office: (r.office as string) ?? null,
    department: (r.department as string) ?? null,
    attribution: (r.attribution as string) ?? null,
    bullets: JSON.parse((r.bullets as string) || '[]'),
    dateline: (r.dateline as string) ?? null,
    byline: (r.byline as string) ?? null,
    status: r.status as Status,
    submitted_by: r.submitted_by as string,
    submitted_at: r.submitted_at as string,
    approved_at: (r.approved_at as string) ?? null,
    fold_date: r.fold_date as string,
    poster_url: (r.poster_url as string) ?? null,
    source_url: (r.source_url as string) ?? null,
  }
}

/* --------------------------------------------------------------- articles */

export interface CreateArticleInput {
  category?: Category
  raw_text: string
  title?: string
  body?: string
  district?: string | null
  language?: Language
  release_no?: string | null
  office?: string | null
  department?: string | null
  attribution?: string | null
  bullets?: string[]
  dateline?: string | null
  byline?: string | null
  status?: Status
  submitted_by?: string
  submitted_at?: string
  approved_at?: string | null
  fold_date: string
  poster_url?: string | null
  source_url?: string | null
}

export async function createArticle(input: CreateArticleInput): Promise<Article> {
  const row = await one(
    `INSERT INTO articles
      (category, raw_text, title, body, district, language, release_no, office, department,
       attribution, bullets, dateline, byline, status, submitted_by, submitted_at, approved_at, fold_date,
       poster_url, source_url)
     VALUES
      (@category, @raw_text, @title, @body, @district, @language, @release_no, @office, @department,
       @attribution, @bullets, @dateline, @byline, @status, @submitted_by, @submitted_at, @approved_at, @fold_date,
       @poster_url, @source_url)
     RETURNING *`,
    {
      category: input.category ?? 'general',
      raw_text: input.raw_text,
      title: input.title ?? '',
      body: input.body ?? input.raw_text,
      district: input.district ?? null,
      language: input.language ?? 'mr',
      release_no: input.release_no ?? null,
      office: input.office ?? null,
      department: input.department ?? null,
      attribution: input.attribution ?? null,
      bullets: JSON.stringify(input.bullets ?? []),
      dateline: input.dateline ?? null,
      byline: input.byline ?? null,
      status: input.status ?? 'pending',
      submitted_by: input.submitted_by ?? 'dlo',
      submitted_at: input.submitted_at ?? new Date().toISOString(),
      approved_at: input.approved_at ?? (input.status === 'approved' ? new Date().toISOString() : null),
      fold_date: input.fold_date,
      poster_url: input.poster_url ?? null,
      source_url: input.source_url ?? null,
    },
  )
  return toArticle(row!)
}

export async function getArticle(id: number): Promise<Article | null> {
  const r = await one('SELECT * FROM articles WHERE id = @id', { id })
  return r ? toArticle(r) : null
}

export async function getArticleBySourceUrl(sourceUrl: string): Promise<Article | null> {
  const r = await one('SELECT * FROM articles WHERE source_url = @sourceUrl', { sourceUrl })
  return r ? toArticle(r) : null
}

export interface ListFilter {
  fold_date?: string
  status?: Status
  category?: Category
  district?: string
  language?: Language
  from?: string
  to?: string
}

export async function listArticles(f: ListFilter = {}): Promise<Article[]> {
  const where: string[] = []
  const params: Record<string, unknown> = {}
  if (f.fold_date) { where.push('fold_date = @fold_date'); params.fold_date = f.fold_date }
  if (f.status) { where.push('status = @status'); params.status = f.status }
  if (f.category) { where.push('category = @category'); params.category = f.category }
  if (f.district) { where.push('district = @district'); params.district = f.district }
  if (f.language) { where.push('language = @language'); params.language = f.language }
  if (f.from) { where.push('fold_date >= @from'); params.from = f.from }
  if (f.to) { where.push('fold_date <= @to'); params.to = f.to }
  const sql =
    'SELECT * FROM articles' +
    (where.length ? ` WHERE ${where.join(' AND ')}` : '') +
    ' ORDER BY id DESC'
  return (await all(sql, params)).map(toArticle)
}

const UPDATABLE = [
  'title', 'body', 'district', 'language', 'release_no', 'office', 'department',
  'attribution', 'dateline', 'byline', 'status', 'category', 'poster_url', 'source_url',
] as const

export async function updateArticle(id: number, patch: Partial<Article>): Promise<Article | null> {
  const sets: string[] = []
  const params: Record<string, unknown> = { id }

  for (const k of UPDATABLE) {
    if (k in patch) { sets.push(`${k} = @${k}`); params[k] = (patch as Record<string, unknown>)[k] ?? null }
  }
  if ('bullets' in patch) { sets.push('bullets = @bullets'); params.bullets = JSON.stringify(patch.bullets ?? []) }
  if (patch.status === 'approved') { sets.push('approved_at = @approved_at'); params.approved_at = new Date().toISOString() }
  if (!sets.length) return getArticle(id)

  await run(`UPDATE articles SET ${sets.join(', ')} WHERE id = @id`, params)
  return getArticle(id)
}

export async function deleteArticle(id: number): Promise<void> {
  await run('DELETE FROM articles WHERE id = @id', { id })
}

/**
 * Suggest the next वृत्त क्र. The desk can always override — DGIPR's counter
 * advances outside this system too, so this is a convenience, not a source of truth.
 *
 * Only all-digit release numbers are considered: Postgres, unlike SQLite, raises
 * on a CAST of '12अ' to integer rather than quietly reading the leading digits.
 */
export async function suggestReleaseNo(): Promise<string> {
  const r = await one(
    `SELECT release_no FROM articles
     WHERE release_no ~ '^[0-9]+$'
     ORDER BY CAST(release_no AS INTEGER) DESC LIMIT 1`,
  )
  const last = r ? Number(r.release_no) : 0
  return String(last + 1)
}

/* ------------------------------------------------------------------ folds */

export async function getFold(date: string): Promise<Fold> {
  const r = await one('SELECT * FROM folds WHERE "date" = @date', { date })
  const approved = await listArticles({ fold_date: date, status: 'approved' })
  const stored: number[] = r ? JSON.parse(r.article_order as string) : []
  const live = new Set(approved.map((a) => a.id))

  // Keep the desk's hand-ordering, drop anything no longer approved, and
  // append newly approved articles at the end. There is no cutoff, so this
  // has to stay correct when an article is approved late.
  const order = stored.filter((id) => live.has(id))
  for (const a of approved) if (!order.includes(a.id)) order.push(a.id)

  return { date, article_order: order, finalized_at: (r?.finalized_at as string) ?? null }
}

export async function setFoldOrder(date: string, order: number[]): Promise<Fold> {
  await run(
    `INSERT INTO folds ("date", article_order) VALUES (@date, @order)
     ON CONFLICT ("date") DO UPDATE SET article_order = EXCLUDED.article_order`,
    { date, order: JSON.stringify(order) },
  )
  return getFold(date)
}

/** Approved articles for a date, in the desk's chosen order. */
export async function foldArticles(date: string): Promise<Article[]> {
  const fold = await getFold(date)
  const approved = await listArticles({ fold_date: date, status: 'approved' })
  const byId = new Map(approved.map((a) => [a.id, a]))
  return fold.article_order.map((id) => byId.get(id)).filter((a): a is Article => !!a)
}

/* ------------------------------------------------------------------ stats */

export interface DistrictCount { district: string; count: number }

export async function districtCounts(from: string, to: string): Promise<DistrictCount[]> {
  const rows = await all(
    `SELECT district, COUNT(*) AS count
     FROM articles
     WHERE status = 'approved' AND district IS NOT NULL
       AND fold_date >= @from AND fold_date <= @to
     GROUP BY district`,
    { from, to },
  )
  // COUNT(*) is a bigint, which pg hands back as a string.
  return rows.map((r) => ({ district: r.district as string, count: Number(r.count) }))
}

/** Daily totals across the range — drives the time slider. */
export async function dailyCounts(from: string, to: string): Promise<{ date: string; count: number }[]> {
  const rows = await all(
    `SELECT fold_date AS date, COUNT(*) AS count
     FROM articles
     WHERE status = 'approved' AND fold_date >= @from AND fold_date <= @to
     GROUP BY fold_date ORDER BY fold_date`,
    { from, to },
  )
  return rows.map((r) => ({ date: r.date as string, count: Number(r.count) }))
}
